# Generated by Django 4.2 on 2025-12-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20, unique=True, verbose_name='USN')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Semester')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Exam Fee Amount')),
                ('fee_paid', models.BooleanField(default=False, verbose_name='Fee Paid')),
            ],
            options={
                'verbose_name': 'Exam Student',
                'verbose_name_plural': 'Exam Students',
            },
        ),
    ]
