# Generated by Django 4.2 on 2025-12-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('semester', models.PositiveSmallIntegerField()),
                ('subject_code', models.CharField(blank=True, max_length=20)),
                ('grade', models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('F', 'F')], max_length=2)),
            ],
        ),
    ]
