# Generated by Django 4.2 on 2025-12-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
