# Generated by Django 4.2 on 2025-12-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10, unique=True, verbose_name='USN')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('subject_code', models.CharField(max_length=10, verbose_name='Subject Code')),
                ('cie_marks', models.IntegerField(verbose_name='CIE Marks')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
